#!/bin/bash
# Helper script to create "binary" wrappers for Python CLI tools
# Auto-generated by Feza
# Usage: ./create_python_binaries.sh

NAME="crow"
MODULE="crow.main"
FUNCTION="main"
TARGET_DIR="build"

mkdir -p "${TARGET_DIR}/macos-arm64"
mkdir -p "${TARGET_DIR}/macos-amd64"
mkdir -p "${TARGET_DIR}/linux-amd64"

# Create wrapper scripts for each target
cat > "${TARGET_DIR}/macos-arm64/${NAME}" << 'EOFWRAPPER'
#!/usr/bin/env python3
import sys
from crow.main import main
if __name__ == "__main__":
    sys.exit(main())
EOFWRAPPER

cat > "${TARGET_DIR}/macos-amd64/${NAME}" << 'EOFWRAPPER'
#!/usr/bin/env python3
import sys
from crow.main import main
if __name__ == "__main__":
    sys.exit(main())
EOFWRAPPER

cat > "${TARGET_DIR}/linux-amd64/${NAME}" << 'EOFWRAPPER'
#!/usr/bin/env python3
import sys
from crow.main import main
if __name__ == "__main__":
    sys.exit(main())
EOFWRAPPER

chmod +x "${TARGET_DIR}/macos-arm64/${NAME}"
chmod +x "${TARGET_DIR}/macos-amd64/${NAME}"
chmod +x "${TARGET_DIR}/linux-amd64/${NAME}"

echo "Created wrapper scripts for ${NAME} in ${TARGET_DIR}/"
echo "These will be packaged by Feza as 'binaries'"
